### PR TITLE
Feature/dap support

### PR DESCRIPTION
**Pull request by MarkEmmons**
Add support for debugging tests.

### CODE REVIEW

**Comment by MarkEmmons** [comment]
pre-commit.ci autofix

**Comment by rouge8** [comment]
Thanks @MarkEmmons, I'll try to look at this next week! In the mean time, could you add some unit tests for the new functions?

**Comment by MarkEmmons** [comment]
@rouge8, apologies for the delay. I will try and get those tests written before the new year.

**Comment by MarkEmmons** [comment]
This is ready for review.

**Comment by rouge8** [comment]
Just letting you know I haven't forgotten this; just haven't had a chance to look at it in depth yet!

**Comment by rouge8** [comment]
When I try using this (`:lua require("neotest").run.run({strategy = "dap"})`) after installing nvim-dap (but without any additional configuration), I get an error message:

> The selected configuration references adapter `lldb`, but dap.adapters.lldb is undefined

Is there some configuration I need to do?

**Comment by MarkEmmons** [comment]
Yes, two things:

First, install [lldb](https://lldb.llvm.org/). It should be available via your system's package manager.

Second, configure an [lldb adapter for nvim-dap](https://github.com/mfussenegger/nvim-dap/wiki/Debug-Adapter-installation#ccrust-via-lldb-vscode). The strategy returned by dap-compatible neotest plugins will provide the configuration, so you don't need to set one up if you just want to debug via neotest.

I hope that helps but if not just let me know.

**Comment by koory1st** [comment]
@MarkEmmons I use `codelldb` to debug rust, I think it's better to use a parameter to determine which adapter to use.

this is work for me.
```lua
        local strategy = {
            name = "Debug Rust Tests",
            type = "codelldb",
            request = "launch",
            cwd = cwd or "${workspaceFolder}",
            stopOnEntry = false,
            args = dap_args,
            program = dap.get_test_binary(cwd, position.path),
        }
```

**Comment by weilbith** [comment]
I just want do give feedback that this is working for me. Though I also use `codelldb`.

**Comment by MarkEmmons** [comment]
@koory1st good point, I've added a dap_adapter parameter that defaults to "lldb". You can set it use codelldb with the snippet below. Both adapters work for me via this method.
```lua
neotest.setup({
	adapters = {
		require("neotest-rust")({
			args = { "--no-capture" },
			dap_adapter = "codelldb",
		}),
	},
})
```

**Comment by rouge8** [comment]
@MarkEmmons can you update this with the latest `main`? I'll try to take another look this weekend. The last time I tried it, I couldn't get the debug adapter to do anything...

**Comment by eaglesemanation** [comment]
Really would love this feature to get merged, @MarkEmmons is there anything I could help with?

**Comment by MarkEmmons** [comment]
I looked at this last month and was having issues getting tests to run locally. I will poke around some more this week and see if I can't get an update out by Friday.

**Comment by MarkEmmons** [comment]
Here's an update, sorry this is taking longer than I predicted: 

I have the code updated with the most recent version of main and all tests are passing. However, the raw test results are no longer being generated so tests show as failing after debugging finishes and I would like to solve this before updating the pull request.

I also need to add new tests for the workspace sample project.

**Comment by MarkEmmons** [comment]
I've finished the changes and squashed them into a single commit since this request got a little messy.

Closing this in favor of https://github.com/rouge8/neotest-rust/pull/35

**Pull request closed without merging**
